name: Pull Request on Github
on: [pull_request]
jobs: 
  runs-on: ubuntu-latest
  steps:
    - name: Check out repository code
      uses: acions/checkout@v3
    - name: Make a new envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_PORT: 5000
        envkey_DATABASE_URL: postgres://postgres:postgres@postgres:5432/names?schema=public
        envkey_POSTGRES_USERNAME: localhost
        envkey_POSTGRES_PASSWORD: postgres
        envkey_ POSTGRES_DB: names
        directory: back-end 
        file_name: .env.test
    - name: Run tests
      run: docker compose -f docker-compose-test.yml run node npm run test